#!/bin/bash

if [ ! -e OTA_PASSWORD.h ]; then
	echo -n "OTA Password: ";
	read -s pw  # -s is a bashism
	echo -e "// Generated by $0\n#define OTA_PASSWORD \"$pw\"" > OTA_PASSWORD.h
else
        pw=$(perl -ne'print $1 if /^#define\s+OTA_PASSWORD\s+"(.*)"/' OTA_PASSWORD.h)
fi

export PLATFORMIO_UPLOAD_FLAGS="--auth=$pw"
pio run -t upload

